"""Portable X-ray system implementation."""

from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
from typing import Optional
import numpy as np

from ..base import ImagingDevice, ImageData, DeviceStatus, DeviceCalibration


class XRayTubeType(Enum):
    """X-ray tube types."""

    ROTATING_ANODE = "rotating_anode"
    STATIONARY_ANODE = "stationary_anode"
    CERAMIC = "ceramic"


@dataclass
class ExposureParameters:
    """X-ray exposure parameters."""

    kvp: float  # Kilovoltage peak
    ma: float  # Milliamperage
    exposure_time: float  # Seconds
    focal_spot: str  # "small" or "large"
    sfd: float  # Source-to-film distance (cm)

    @property
    def mas(self) -> float:
        """Calculate mAs (milliampere-seconds)."""
        return self.ma * self.exposure_time

    def validate(self) -> bool:
        """Validate exposure parameters are within safe ranges."""
        if not (40 <= self.kvp <= 150):
            return False
        if not (0.5 <= self.ma <= 500):
            return False
        if not (0.001 <= self.exposure_time <= 10):
            return False
        if not (50 <= self.sfd <= 200):
            return False
        return True


@dataclass
class XRayTube:
    """X-ray tube specifications."""

    tube_type: XRayTubeType
    max_kvp: float
    max_ma: float
    focal_spot_sizes: tuple[float, float]  # (small, large) in mm
    anode_angle: float  # degrees
    heat_capacity: float  # HU (Heat Units)
    current_heat: float = 0.0

    def calculate_heat_units(self, kvp: float, ma: float, time: float) -> float:
        """Calculate heat units generated by exposure."""
        return kvp * ma * time

    def can_expose(self, kvp: float, ma: float, time: float) -> bool:
        """Check if tube can handle the exposure."""
        hu = self.calculate_heat_units(kvp, ma, time)
        return (self.current_heat + hu) < self.heat_capacity

    def add_heat(self, kvp: float, ma: float, time: float):
        """Add heat from exposure."""
        self.current_heat += self.calculate_heat_units(kvp, ma, time)

    def cool_down(self, cooling_rate: float = 1000.0, time: float = 1.0):
        """Simulate tube cooling."""
        self.current_heat = max(0, self.current_heat - cooling_rate * time)


class PortableXRay(ImagingDevice):
    """Portable X-ray system implementation."""

    def __init__(
        self,
        device_id: str,
        device_name: str,
        manufacturer: str = "",
        model: str = "",
        max_kvp: float = 125,
        max_ma: float = 320,
    ):
        super().__init__(device_id, device_name, manufacturer, model)

        self._tube = XRayTube(
            tube_type=XRayTubeType.ROTATING_ANODE,
            max_kvp=max_kvp,
            max_ma=max_ma,
            focal_spot_sizes=(0.6, 1.2),
            anode_angle=12.0,
            heat_capacity=300000,
        )

        self._default_exposure = ExposureParameters(
            kvp=80,
            ma=200,
            exposure_time=0.05,
            focal_spot="large",
            sfd=100,
        )

        self._battery_level: float = 100.0
        self._exposure_count: int = 0
        self._detector: Optional["XRayDetector"] = None

    def initialize(self) -> bool:
        """Initialize the portable X-ray system."""
        try:
            self._status = DeviceStatus.INITIALIZING

            # Check battery
            if self._battery_level < 10:
                raise RuntimeError("Battery too low for operation")

            # Initialize tube warm-up
            self._tube_warmup()

            # Self-test
            self._run_self_test()

            self._status = DeviceStatus.READY
            return True
        except Exception as e:
            self.log_error(f"Initialization failed: {str(e)}")
            return False

    def _tube_warmup(self):
        """Perform tube warm-up sequence."""
        # Simulated warm-up exposures
        warmup_sequence = [
            (50, 10, 0.1),
            (60, 20, 0.1),
            (70, 50, 0.1),
        ]
        for kvp, ma, time in warmup_sequence:
            self._tube.add_heat(kvp, ma, time)

    def _run_self_test(self):
        """Run system self-test."""
        # Verify tube filament
        # Check collimator
        # Verify detector communication
        pass

    def shutdown(self) -> bool:
        """Shutdown the system safely."""
        try:
            self._status = DeviceStatus.OFFLINE
            return True
        except Exception as e:
            self.log_error(f"Shutdown failed: {str(e)}")
            return False

    def acquire(
        self,
        exposure_params: Optional[ExposureParameters] = None,
        anatomical_region: str = "chest",
        **params,
    ) -> ImageData:
        """Acquire X-ray image."""
        if not self.is_ready:
            raise RuntimeError(f"Device not ready. Current status: {self._status}")

        if exposure_params is None:
            exposure_params = self._get_default_exposure(anatomical_region)

        if not exposure_params.validate():
            raise ValueError("Invalid exposure parameters")

        if not self._tube.can_expose(
            exposure_params.kvp,
            exposure_params.ma,
            exposure_params.exposure_time,
        ):
            raise RuntimeError("Tube heat capacity exceeded. Allow cooling.")

        self._status = DeviceStatus.ACQUIRING

        try:
            # Simulate X-ray exposure
            image_data = self._perform_exposure(exposure_params)

            # Update tube heat
            self._tube.add_heat(
                exposure_params.kvp,
                exposure_params.ma,
                exposure_params.exposure_time,
            )

            # Update battery
            self._battery_level -= 0.5

            self._exposure_count += 1
            self._last_acquisition = datetime.now()
            self._status = DeviceStatus.READY

            return ImageData(
                data=image_data,
                timestamp=self._last_acquisition,
                metadata={
                    "modality": "xray",
                    "kvp": exposure_params.kvp,
                    "ma": exposure_params.ma,
                    "exposure_time": exposure_params.exposure_time,
                    "mas": exposure_params.mas,
                    "sfd_cm": exposure_params.sfd,
                    "focal_spot": exposure_params.focal_spot,
                    "anatomical_region": anatomical_region,
                    "exposure_number": self._exposure_count,
                },
                device_id=self.device_id,
                modality="xray",
            )
        except Exception as e:
            self.log_error(f"Acquisition failed: {str(e)}")
            raise

    def _get_default_exposure(self, anatomical_region: str) -> ExposureParameters:
        """Get default exposure parameters for anatomical region."""
        presets = {
            "chest": ExposureParameters(110, 200, 0.02, "large", 180),
            "hand": ExposureParameters(50, 100, 0.01, "small", 100),
            "pelvis": ExposureParameters(80, 320, 0.05, "large", 100),
            "spine": ExposureParameters(85, 250, 0.04, "large", 100),
            "skull": ExposureParameters(75, 200, 0.03, "large", 100),
            "abdomen": ExposureParameters(80, 250, 0.05, "large", 100),
        }
        return presets.get(anatomical_region, self._default_exposure)

    def _perform_exposure(self, params: ExposureParameters) -> np.ndarray:
        """Perform X-ray exposure and generate image."""
        # Simulate detector response
        detector_size = (2048, 2048)

        # Generate base image with quantum noise
        exposure_level = params.kvp * params.mas / 1000
        base_intensity = exposure_level * 1000

        # Poisson noise (quantum mottle)
        image = np.random.poisson(base_intensity, detector_size).astype(np.float64)

        # Add some anatomical structure simulation
        image = self._add_simulated_anatomy(image, params)

        # Apply logarithmic transformation
        image = np.log1p(image)

        # Normalize to 14-bit range (typical for DR)
        image = (image - image.min()) / (image.max() - image.min()) * 16383

        return image.astype(np.uint16)

    def _add_simulated_anatomy(
        self,
        image: np.ndarray,
        params: ExposureParameters,
    ) -> np.ndarray:
        """Add simulated anatomical structures."""
        h, w = image.shape

        # Add some circular structures (simulate ribs/organs)
        y, x = np.ogrid[:h, :w]
        for _ in range(10):
            cx, cy = np.random.randint(w // 4, 3 * w // 4), np.random.randint(h // 4, 3 * h // 4)
            r = np.random.randint(50, 200)
            attenuation = np.random.uniform(0.3, 0.8)
            mask = (x - cx) ** 2 + (y - cy) ** 2 < r**2
            image[mask] *= attenuation

        return image

    def calibrate(self, **params) -> DeviceCalibration:
        """Calibrate the X-ray system."""
        self._status = DeviceStatus.MAINTENANCE

        try:
            calibration_params = {
                "tube_output": self._calibrate_tube_output(),
                "detector_uniformity": self._calibrate_detector_uniformity(),
                "aec_calibration": self._calibrate_aec(),
            }

            self._calibration = DeviceCalibration(
                calibration_date=datetime.now(),
                calibration_parameters=calibration_params,
                is_valid=True,
                expiry_date=datetime.now() + timedelta(days=365),
            )

            self._status = DeviceStatus.READY
            return self._calibration
        except Exception as e:
            self.log_error(f"Calibration failed: {str(e)}")
            raise

    def _calibrate_tube_output(self) -> dict:
        """Calibrate X-ray tube output."""
        return {
            "output_consistency": 0.98,
            "kvp_accuracy": 0.99,
            "ma_accuracy": 0.97,
        }

    def _calibrate_detector_uniformity(self) -> dict:
        """Calibrate detector uniformity."""
        return {
            "uniformity_coefficient": 0.95,
            "dead_pixels": 12,
            "gain_correction_applied": True,
        }

    def _calibrate_aec(self) -> dict:
        """Calibrate automatic exposure control."""
        return {
            "aec_sensitivity": 1.0,
            "backup_time": 2.0,
            "density_settings": [-2, -1, 0, 1, 2],
        }

    def attach_detector(self, detector: "XRayDetector"):
        """Attach an X-ray detector to the system."""
        self._detector = detector

    @property
    def battery_level(self) -> float:
        """Get current battery level."""
        return self._battery_level

    @property
    def tube_heat_percentage(self) -> float:
        """Get current tube heat as percentage of capacity."""
        return (self._tube.current_heat / self._tube.heat_capacity) * 100

    def set_collimation(self, field_size: tuple[float, float]):
        """Set collimator field size."""
        # Collimation setting would be implemented here
        pass
